package org.uestc.gout.model;

public class UsertypeAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertype_auth.id
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertype_auth.usertypeid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer usertypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usertype_auth.authid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer authid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertype_auth.id
     *
     * @return the value of usertype_auth.id
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertype_auth.id
     *
     * @param id the value for usertype_auth.id
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertype_auth.usertypeid
     *
     * @return the value of usertype_auth.usertypeid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getUsertypeid() {
        return usertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertype_auth.usertypeid
     *
     * @param usertypeid the value for usertype_auth.usertypeid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setUsertypeid(Integer usertypeid) {
        this.usertypeid = usertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usertype_auth.authid
     *
     * @return the value of usertype_auth.authid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usertype_auth.authid
     *
     * @param authid the value for usertype_auth.authid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setAuthid(Integer authid) {
        this.authid = authid;
    }
}