module.exports = {
  id: {
    type: 'serial',
    key: true
  },
  patientid: Number,
  docterid: Number,
  gender: Number,
  height: Number,
  weight: Number,
  age: Number,
  nation: String,
  nativeplace: String,
  job: String,
  phonenumber: String,
  email: String,
  firstvisitdate: Date,
  isrelativegout: Number,
  realname: String,
  idcardnumber: String,
  havehypertension: Number,
  havediabetes: Number,
  haveheartdisease: Number,
  havehlp: Number,
  haveotherdisease: Number,
  hypertensionmedicine: String,
  diabetesmedicine: String,
  heartdiseasemedicine: String,
  hlpmedicine: String,
  otherdiseasemedicine: String,
  havetophus: Number,
  b_modeus: Number,
}