module.exports = {
  habitid: {
    type: 'serial',
    key: true
  },
  userid: Number,
  staplefood: Number,
  staplefoodamount: Number,
  taste: Number,
  dietarypreference: Number,
  drinktype: Number,
  fishpd: Number,
  seafoodpd: Number,
  beefpd: Number,
  porkpd: Number,
  poultrypd: Number,
  visceralpd: Number,
  vegetablepd: Number,
  beanpd: Number,
  eggpd: Number,
  nutpd: Number,
  fruitpd: Number,
  saltpd: Number,
  beerpd: Number,
  milkpd: Number,
  liquorpd: Number,
  wirepd: Number,
  teatype: Number,
  teapd: Number,
  createtime: Date,
  modifytime: Date
}