package org.uestc.gout.dao;

import org.uestc.gout.model.Reminder;

public interface ReminderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminder
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int deleteByPrimaryKey(Integer reminderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminder
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int insert(Reminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminder
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int insertSelective(Reminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminder
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    Reminder selectByPrimaryKey(Integer reminderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminder
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int updateByPrimaryKeySelective(Reminder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reminder
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int updateByPrimaryKey(Reminder record);
}