package org.uestc.gout.dao;

import org.uestc.gout.model.Weekhabit;

public interface WeekhabitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekhabit
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int deleteByPrimaryKey(Integer habitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekhabit
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int insert(Weekhabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekhabit
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int insertSelective(Weekhabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekhabit
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    Weekhabit selectByPrimaryKey(Integer habitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekhabit
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int updateByPrimaryKeySelective(Weekhabit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weekhabit
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    int updateByPrimaryKey(Weekhabit record);
}