package org.uestc.gout.model;

import java.util.Date;

public class Messgae {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.msgid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer msgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.rcvuserid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer rcvuserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.sduserid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer sduserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.datetime
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Date datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.isrcv
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte isrcv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.msgid
     *
     * @return the value of message.msgid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.msgid
     *
     * @param msgid the value for message.msgid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setMsgid(Integer msgid) {
        this.msgid = msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.rcvuserid
     *
     * @return the value of message.rcvuserid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getRcvuserid() {
        return rcvuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.rcvuserid
     *
     * @param rcvuserid the value for message.rcvuserid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setRcvuserid(Integer rcvuserid) {
        this.rcvuserid = rcvuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.sduserid
     *
     * @return the value of message.sduserid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getSduserid() {
        return sduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.sduserid
     *
     * @param sduserid the value for message.sduserid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setSduserid(Integer sduserid) {
        this.sduserid = sduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.datetime
     *
     * @return the value of message.datetime
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Date getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.datetime
     *
     * @param datetime the value for message.datetime
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.isrcv
     *
     * @return the value of message.isrcv
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getIsrcv() {
        return isrcv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.isrcv
     *
     * @param isrcv the value for message.isrcv
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setIsrcv(Byte isrcv) {
        this.isrcv = isrcv;
    }
}