package org.uestc.gout.model;

import java.math.BigDecimal;

public class Monthyassay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.assayid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer assayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.userid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.assay_docid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer assayDocid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.diseasecourse
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer diseasecourse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.isjointpain
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Boolean isjointpain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.painpart
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String painpart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.isjointswelling
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Boolean isjointswelling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.swellingpart
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String swellingpart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.isdietchange
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Boolean isdietchange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.isexercise
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Boolean isexercise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.esr
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal esr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.crp
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal crp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.ua
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal ua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.ganyousanzhi
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal ganyousanzhi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.totalcholesterol
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal totalcholesterol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.tmdasajzym
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal tmdasajzym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.basajzym
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal basajzym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.cr
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal cr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.cbc
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String cbc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.havetophus
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte havetophus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.b_modeus
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte bModeus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.havehypertension
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte havehypertension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.havediabetes
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte havediabetes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.haveheartdisease
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte haveheartdisease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.havehlp
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte havehlp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.haveotherdisease
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte haveotherdisease;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.hypertensionmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String hypertensionmedicine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.diabetesmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String diabetesmedicine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.heartdiseasemedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String heartdiseasemedicine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.hlpmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String hlpmedicine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.otherdiseasemedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private String otherdiseasemedicine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.gcsdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal gcsdosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.colcdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal colcdosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.allopurinoldosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal allopurinoldosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.benzbromaronedosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal benzbromaronedosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.nsaiddosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal nsaiddosage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column monthyassay.febuxostatdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private BigDecimal febuxostatdosage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.assayid
     *
     * @return the value of monthyassay.assayid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getAssayid() {
        return assayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.assayid
     *
     * @param assayid the value for monthyassay.assayid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setAssayid(Integer assayid) {
        this.assayid = assayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.userid
     *
     * @return the value of monthyassay.userid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.userid
     *
     * @param userid the value for monthyassay.userid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.assay_docid
     *
     * @return the value of monthyassay.assay_docid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getAssayDocid() {
        return assayDocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.assay_docid
     *
     * @param assayDocid the value for monthyassay.assay_docid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setAssayDocid(Integer assayDocid) {
        this.assayDocid = assayDocid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.diseasecourse
     *
     * @return the value of monthyassay.diseasecourse
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getDiseasecourse() {
        return diseasecourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.diseasecourse
     *
     * @param diseasecourse the value for monthyassay.diseasecourse
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setDiseasecourse(Integer diseasecourse) {
        this.diseasecourse = diseasecourse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.isjointpain
     *
     * @return the value of monthyassay.isjointpain
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Boolean getIsjointpain() {
        return isjointpain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.isjointpain
     *
     * @param isjointpain the value for monthyassay.isjointpain
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setIsjointpain(Boolean isjointpain) {
        this.isjointpain = isjointpain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.painpart
     *
     * @return the value of monthyassay.painpart
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getPainpart() {
        return painpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.painpart
     *
     * @param painpart the value for monthyassay.painpart
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setPainpart(String painpart) {
        this.painpart = painpart == null ? null : painpart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.isjointswelling
     *
     * @return the value of monthyassay.isjointswelling
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Boolean getIsjointswelling() {
        return isjointswelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.isjointswelling
     *
     * @param isjointswelling the value for monthyassay.isjointswelling
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setIsjointswelling(Boolean isjointswelling) {
        this.isjointswelling = isjointswelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.swellingpart
     *
     * @return the value of monthyassay.swellingpart
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getSwellingpart() {
        return swellingpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.swellingpart
     *
     * @param swellingpart the value for monthyassay.swellingpart
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setSwellingpart(String swellingpart) {
        this.swellingpart = swellingpart == null ? null : swellingpart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.isdietchange
     *
     * @return the value of monthyassay.isdietchange
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Boolean getIsdietchange() {
        return isdietchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.isdietchange
     *
     * @param isdietchange the value for monthyassay.isdietchange
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setIsdietchange(Boolean isdietchange) {
        this.isdietchange = isdietchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.isexercise
     *
     * @return the value of monthyassay.isexercise
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Boolean getIsexercise() {
        return isexercise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.isexercise
     *
     * @param isexercise the value for monthyassay.isexercise
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setIsexercise(Boolean isexercise) {
        this.isexercise = isexercise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.esr
     *
     * @return the value of monthyassay.esr
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getEsr() {
        return esr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.esr
     *
     * @param esr the value for monthyassay.esr
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setEsr(BigDecimal esr) {
        this.esr = esr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.crp
     *
     * @return the value of monthyassay.crp
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getCrp() {
        return crp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.crp
     *
     * @param crp the value for monthyassay.crp
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setCrp(BigDecimal crp) {
        this.crp = crp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.ua
     *
     * @return the value of monthyassay.ua
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getUa() {
        return ua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.ua
     *
     * @param ua the value for monthyassay.ua
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setUa(BigDecimal ua) {
        this.ua = ua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.ganyousanzhi
     *
     * @return the value of monthyassay.ganyousanzhi
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getGanyousanzhi() {
        return ganyousanzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.ganyousanzhi
     *
     * @param ganyousanzhi the value for monthyassay.ganyousanzhi
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setGanyousanzhi(BigDecimal ganyousanzhi) {
        this.ganyousanzhi = ganyousanzhi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.totalcholesterol
     *
     * @return the value of monthyassay.totalcholesterol
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getTotalcholesterol() {
        return totalcholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.totalcholesterol
     *
     * @param totalcholesterol the value for monthyassay.totalcholesterol
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setTotalcholesterol(BigDecimal totalcholesterol) {
        this.totalcholesterol = totalcholesterol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.tmdasajzym
     *
     * @return the value of monthyassay.tmdasajzym
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getTmdasajzym() {
        return tmdasajzym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.tmdasajzym
     *
     * @param tmdasajzym the value for monthyassay.tmdasajzym
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setTmdasajzym(BigDecimal tmdasajzym) {
        this.tmdasajzym = tmdasajzym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.basajzym
     *
     * @return the value of monthyassay.basajzym
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getBasajzym() {
        return basajzym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.basajzym
     *
     * @param basajzym the value for monthyassay.basajzym
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setBasajzym(BigDecimal basajzym) {
        this.basajzym = basajzym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.cr
     *
     * @return the value of monthyassay.cr
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getCr() {
        return cr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.cr
     *
     * @param cr the value for monthyassay.cr
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setCr(BigDecimal cr) {
        this.cr = cr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.cbc
     *
     * @return the value of monthyassay.cbc
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getCbc() {
        return cbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.cbc
     *
     * @param cbc the value for monthyassay.cbc
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setCbc(String cbc) {
        this.cbc = cbc == null ? null : cbc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.havetophus
     *
     * @return the value of monthyassay.havetophus
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getHavetophus() {
        return havetophus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.havetophus
     *
     * @param havetophus the value for monthyassay.havetophus
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHavetophus(Byte havetophus) {
        this.havetophus = havetophus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.b_modeus
     *
     * @return the value of monthyassay.b_modeus
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getbModeus() {
        return bModeus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.b_modeus
     *
     * @param bModeus the value for monthyassay.b_modeus
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setbModeus(Byte bModeus) {
        this.bModeus = bModeus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.havehypertension
     *
     * @return the value of monthyassay.havehypertension
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getHavehypertension() {
        return havehypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.havehypertension
     *
     * @param havehypertension the value for monthyassay.havehypertension
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHavehypertension(Byte havehypertension) {
        this.havehypertension = havehypertension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.havediabetes
     *
     * @return the value of monthyassay.havediabetes
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getHavediabetes() {
        return havediabetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.havediabetes
     *
     * @param havediabetes the value for monthyassay.havediabetes
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHavediabetes(Byte havediabetes) {
        this.havediabetes = havediabetes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.haveheartdisease
     *
     * @return the value of monthyassay.haveheartdisease
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getHaveheartdisease() {
        return haveheartdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.haveheartdisease
     *
     * @param haveheartdisease the value for monthyassay.haveheartdisease
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHaveheartdisease(Byte haveheartdisease) {
        this.haveheartdisease = haveheartdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.havehlp
     *
     * @return the value of monthyassay.havehlp
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getHavehlp() {
        return havehlp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.havehlp
     *
     * @param havehlp the value for monthyassay.havehlp
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHavehlp(Byte havehlp) {
        this.havehlp = havehlp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.haveotherdisease
     *
     * @return the value of monthyassay.haveotherdisease
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getHaveotherdisease() {
        return haveotherdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.haveotherdisease
     *
     * @param haveotherdisease the value for monthyassay.haveotherdisease
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHaveotherdisease(Byte haveotherdisease) {
        this.haveotherdisease = haveotherdisease;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.hypertensionmedicine
     *
     * @return the value of monthyassay.hypertensionmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getHypertensionmedicine() {
        return hypertensionmedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.hypertensionmedicine
     *
     * @param hypertensionmedicine the value for monthyassay.hypertensionmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHypertensionmedicine(String hypertensionmedicine) {
        this.hypertensionmedicine = hypertensionmedicine == null ? null : hypertensionmedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.diabetesmedicine
     *
     * @return the value of monthyassay.diabetesmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getDiabetesmedicine() {
        return diabetesmedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.diabetesmedicine
     *
     * @param diabetesmedicine the value for monthyassay.diabetesmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setDiabetesmedicine(String diabetesmedicine) {
        this.diabetesmedicine = diabetesmedicine == null ? null : diabetesmedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.heartdiseasemedicine
     *
     * @return the value of monthyassay.heartdiseasemedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getHeartdiseasemedicine() {
        return heartdiseasemedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.heartdiseasemedicine
     *
     * @param heartdiseasemedicine the value for monthyassay.heartdiseasemedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHeartdiseasemedicine(String heartdiseasemedicine) {
        this.heartdiseasemedicine = heartdiseasemedicine == null ? null : heartdiseasemedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.hlpmedicine
     *
     * @return the value of monthyassay.hlpmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getHlpmedicine() {
        return hlpmedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.hlpmedicine
     *
     * @param hlpmedicine the value for monthyassay.hlpmedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHlpmedicine(String hlpmedicine) {
        this.hlpmedicine = hlpmedicine == null ? null : hlpmedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.otherdiseasemedicine
     *
     * @return the value of monthyassay.otherdiseasemedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public String getOtherdiseasemedicine() {
        return otherdiseasemedicine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.otherdiseasemedicine
     *
     * @param otherdiseasemedicine the value for monthyassay.otherdiseasemedicine
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setOtherdiseasemedicine(String otherdiseasemedicine) {
        this.otherdiseasemedicine = otherdiseasemedicine == null ? null : otherdiseasemedicine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.gcsdosage
     *
     * @return the value of monthyassay.gcsdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getGcsdosage() {
        return gcsdosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.gcsdosage
     *
     * @param gcsdosage the value for monthyassay.gcsdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setGcsdosage(BigDecimal gcsdosage) {
        this.gcsdosage = gcsdosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.colcdosage
     *
     * @return the value of monthyassay.colcdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getColcdosage() {
        return colcdosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.colcdosage
     *
     * @param colcdosage the value for monthyassay.colcdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setColcdosage(BigDecimal colcdosage) {
        this.colcdosage = colcdosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.allopurinoldosage
     *
     * @return the value of monthyassay.allopurinoldosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getAllopurinoldosage() {
        return allopurinoldosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.allopurinoldosage
     *
     * @param allopurinoldosage the value for monthyassay.allopurinoldosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setAllopurinoldosage(BigDecimal allopurinoldosage) {
        this.allopurinoldosage = allopurinoldosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.benzbromaronedosage
     *
     * @return the value of monthyassay.benzbromaronedosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getBenzbromaronedosage() {
        return benzbromaronedosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.benzbromaronedosage
     *
     * @param benzbromaronedosage the value for monthyassay.benzbromaronedosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setBenzbromaronedosage(BigDecimal benzbromaronedosage) {
        this.benzbromaronedosage = benzbromaronedosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.nsaiddosage
     *
     * @return the value of monthyassay.nsaiddosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getNsaiddosage() {
        return nsaiddosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.nsaiddosage
     *
     * @param nsaiddosage the value for monthyassay.nsaiddosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setNsaiddosage(BigDecimal nsaiddosage) {
        this.nsaiddosage = nsaiddosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column monthyassay.febuxostatdosage
     *
     * @return the value of monthyassay.febuxostatdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public BigDecimal getFebuxostatdosage() {
        return febuxostatdosage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column monthyassay.febuxostatdosage
     *
     * @param febuxostatdosage the value for monthyassay.febuxostatdosage
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setFebuxostatdosage(BigDecimal febuxostatdosage) {
        this.febuxostatdosage = febuxostatdosage;
    }
}