package org.uestc.gout.model;

public class Weekhabit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.habitid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer habitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.userid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.staplefood
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte staplefood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.staplefoodamount
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte staplefoodamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.taste
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte taste;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.dietarypreference
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte dietarypreference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.drinktype
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte drinktype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.fishpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte fishpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.seafoodpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte seafoodpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.beefpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte beefpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.porkpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte porkpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.poultrypd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte poultrypd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.visceralpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte visceralpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.vegetablepd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte vegetablepd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.beanpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte beanpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.eggpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte eggpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.nutpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte nutpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.fruitpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte fruitpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.saltpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte saltpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.beerpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte beerpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.milkpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte milkpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.liquorpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte liquorpd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.wirepd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte wirepd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.teatype
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte teatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weekhabit.teapd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    private Byte teapd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.habitid
     *
     * @return the value of weekhabit.habitid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getHabitid() {
        return habitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.habitid
     *
     * @param habitid the value for weekhabit.habitid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setHabitid(Integer habitid) {
        this.habitid = habitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.userid
     *
     * @return the value of weekhabit.userid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.userid
     *
     * @param userid the value for weekhabit.userid
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.staplefood
     *
     * @return the value of weekhabit.staplefood
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getStaplefood() {
        return staplefood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.staplefood
     *
     * @param staplefood the value for weekhabit.staplefood
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setStaplefood(Byte staplefood) {
        this.staplefood = staplefood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.staplefoodamount
     *
     * @return the value of weekhabit.staplefoodamount
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getStaplefoodamount() {
        return staplefoodamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.staplefoodamount
     *
     * @param staplefoodamount the value for weekhabit.staplefoodamount
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setStaplefoodamount(Byte staplefoodamount) {
        this.staplefoodamount = staplefoodamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.taste
     *
     * @return the value of weekhabit.taste
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getTaste() {
        return taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.taste
     *
     * @param taste the value for weekhabit.taste
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setTaste(Byte taste) {
        this.taste = taste;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.dietarypreference
     *
     * @return the value of weekhabit.dietarypreference
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getDietarypreference() {
        return dietarypreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.dietarypreference
     *
     * @param dietarypreference the value for weekhabit.dietarypreference
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setDietarypreference(Byte dietarypreference) {
        this.dietarypreference = dietarypreference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.drinktype
     *
     * @return the value of weekhabit.drinktype
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getDrinktype() {
        return drinktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.drinktype
     *
     * @param drinktype the value for weekhabit.drinktype
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setDrinktype(Byte drinktype) {
        this.drinktype = drinktype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.fishpd
     *
     * @return the value of weekhabit.fishpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getFishpd() {
        return fishpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.fishpd
     *
     * @param fishpd the value for weekhabit.fishpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setFishpd(Byte fishpd) {
        this.fishpd = fishpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.seafoodpd
     *
     * @return the value of weekhabit.seafoodpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getSeafoodpd() {
        return seafoodpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.seafoodpd
     *
     * @param seafoodpd the value for weekhabit.seafoodpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setSeafoodpd(Byte seafoodpd) {
        this.seafoodpd = seafoodpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.beefpd
     *
     * @return the value of weekhabit.beefpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getBeefpd() {
        return beefpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.beefpd
     *
     * @param beefpd the value for weekhabit.beefpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setBeefpd(Byte beefpd) {
        this.beefpd = beefpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.porkpd
     *
     * @return the value of weekhabit.porkpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getPorkpd() {
        return porkpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.porkpd
     *
     * @param porkpd the value for weekhabit.porkpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setPorkpd(Byte porkpd) {
        this.porkpd = porkpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.poultrypd
     *
     * @return the value of weekhabit.poultrypd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getPoultrypd() {
        return poultrypd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.poultrypd
     *
     * @param poultrypd the value for weekhabit.poultrypd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setPoultrypd(Byte poultrypd) {
        this.poultrypd = poultrypd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.visceralpd
     *
     * @return the value of weekhabit.visceralpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getVisceralpd() {
        return visceralpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.visceralpd
     *
     * @param visceralpd the value for weekhabit.visceralpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setVisceralpd(Byte visceralpd) {
        this.visceralpd = visceralpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.vegetablepd
     *
     * @return the value of weekhabit.vegetablepd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getVegetablepd() {
        return vegetablepd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.vegetablepd
     *
     * @param vegetablepd the value for weekhabit.vegetablepd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setVegetablepd(Byte vegetablepd) {
        this.vegetablepd = vegetablepd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.beanpd
     *
     * @return the value of weekhabit.beanpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getBeanpd() {
        return beanpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.beanpd
     *
     * @param beanpd the value for weekhabit.beanpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setBeanpd(Byte beanpd) {
        this.beanpd = beanpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.eggpd
     *
     * @return the value of weekhabit.eggpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getEggpd() {
        return eggpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.eggpd
     *
     * @param eggpd the value for weekhabit.eggpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setEggpd(Byte eggpd) {
        this.eggpd = eggpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.nutpd
     *
     * @return the value of weekhabit.nutpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getNutpd() {
        return nutpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.nutpd
     *
     * @param nutpd the value for weekhabit.nutpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setNutpd(Byte nutpd) {
        this.nutpd = nutpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.fruitpd
     *
     * @return the value of weekhabit.fruitpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getFruitpd() {
        return fruitpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.fruitpd
     *
     * @param fruitpd the value for weekhabit.fruitpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setFruitpd(Byte fruitpd) {
        this.fruitpd = fruitpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.saltpd
     *
     * @return the value of weekhabit.saltpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getSaltpd() {
        return saltpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.saltpd
     *
     * @param saltpd the value for weekhabit.saltpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setSaltpd(Byte saltpd) {
        this.saltpd = saltpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.beerpd
     *
     * @return the value of weekhabit.beerpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getBeerpd() {
        return beerpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.beerpd
     *
     * @param beerpd the value for weekhabit.beerpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setBeerpd(Byte beerpd) {
        this.beerpd = beerpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.milkpd
     *
     * @return the value of weekhabit.milkpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getMilkpd() {
        return milkpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.milkpd
     *
     * @param milkpd the value for weekhabit.milkpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setMilkpd(Byte milkpd) {
        this.milkpd = milkpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.liquorpd
     *
     * @return the value of weekhabit.liquorpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getLiquorpd() {
        return liquorpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.liquorpd
     *
     * @param liquorpd the value for weekhabit.liquorpd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setLiquorpd(Byte liquorpd) {
        this.liquorpd = liquorpd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.wirepd
     *
     * @return the value of weekhabit.wirepd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getWirepd() {
        return wirepd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.wirepd
     *
     * @param wirepd the value for weekhabit.wirepd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setWirepd(Byte wirepd) {
        this.wirepd = wirepd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.teatype
     *
     * @return the value of weekhabit.teatype
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getTeatype() {
        return teatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.teatype
     *
     * @param teatype the value for weekhabit.teatype
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setTeatype(Byte teatype) {
        this.teatype = teatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weekhabit.teapd
     *
     * @return the value of weekhabit.teapd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public Byte getTeapd() {
        return teapd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weekhabit.teapd
     *
     * @param teapd the value for weekhabit.teapd
     *
     * @mbggenerated Wed May 04 20:10:01 CST 2016
     */
    public void setTeapd(Byte teapd) {
        this.teapd = teapd;
    }
}